### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by lc3t35** [expo/vector-icons#56]
SDK27, exp --version 55.0.5
```
% react-native link
...
Platform 'ios' module @expo/vector-icons has been successfully linked
...
```
At build with Xcode 9.2, I have the build error in Librairies/RNVectoricons.xcodeproj/RNVectorIconsManager/RNVectorIconsManager.h : 
```
'RCTBridgeModule.h' file not found
```

**Comment by lc3t35** [comment]
After checking the HEADER Search Paths, I suspect a problem with the path "@expo/vector-icons" when referencing the path with $(SRCROOT) ...

**Comment by bportman** [comment]
I'm wrestling with this issue in a detached expokit project with SDK29.  I've tried manually putting that line in the podfile, updating Header Search Paths on the RNVectorIcons.xcodeproj in Xcode, and scoured the github issues for this fork as well as the main react-native-vector-icons repo.  At times I'm able to get the issue to go away and give me another error such as the "linker failed with code 1" and "duplicate symbols".  

I even went to the point of deleting my ios/android directories and recreating them with exp detach, essentially working my way through the entire process repeatedly and the issue keeps coming back.

Any help would be greatly appreciated!

**Comment by bportman** [comment]
Update - this keeps happening and my solution works, it's really annoying.  Sometimes I have to do the following 2 or 3 times before it works:

1. Clean in Xcode
2. `cd ios && rm -rf Pods Podfile.lock build && pod install && cd .. && react-native run-ios --device "bportman’s iPhone"

Can we really consider this a closed issue?
